linters:
  ImportPath:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  QualifyingElement:
    allow_element_with_attribute: true
  PropertySpelling:
    extra_properties:
      - text-size-adjust
