language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rails' ]; then cd .. && eval "mv $currentfolder generator-rails" && cd generator-rails; fi

